name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "30 1 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: "This issue doesn't seem to have got much attention recently; marking as stale. Thanks for your contributions!"
        stale-pr-message: "This PR doesn't seem to have got much attention recently; marking as stale. Thanks for your contributions!"
        stale-issue-label: 'stale'
        stale-pr-label: 'stale'
